/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.1.0/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
kotlin("jvm") version "2.2.0" apply false
}

allprojects {

repositories {
    mavenCentral()
}

}

subprojects {

group = "agent"

version = "0.1.0"

}
