/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.1.0/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "autonomous-system-agent"

include(
    ":apps:agent-cli",

    ":modules:shared",
    ":modules:planner",
    ":modules:executor",
    ":modules:policy",
    ":modules:context",
    ":modules:tools",
    ":modules:providers",
    ":modules:audit",
    ":modules:sandbox",
    ":modules:runtime",
)
